### ISSUE TITLE
Memory Leak with CordovaWebView

### ISSUE THREAD

**Issue by jarradh** [syng-io/syng-client#13]
08-10 19:01:13.937 1586-4885/io.syng D/LeakCanary﹕ In io.syng:1.0:1.
08-10 19:01:13.937 1586-4885/io.syng D/LeakCanary﹕ * io.syng.fragment.WebViewFragment has leaked:
08-10 19:01:13.937 1586-4885/io.syng D/LeakCanary﹕ * GC ROOT thread java.lang.Thread.<Java Local, Native Stack> (named 'pool-13-thread-1')
08-10 19:01:13.937 1586-4885/io.syng D/LeakCanary﹕ * references org.apache.cordova.CordovaWebViewImpl$2.this$0 (anonymous class implements java.lang.Runnable)
08-10 19:01:13.937 1586-4885/io.syng D/LeakCanary﹕ * references org.apache.cordova.CordovaWebViewImpl.cordova
08-10 19:01:13.937 1586-4885/io.syng D/LeakCanary﹕ * references io.syng.fragment.WebViewFragment$1.this$0 (anonymous class extends org.apache.cordova.CordovaInterfaceImpl)
08-10 19:01:13.937 1586-4885/io.syng D/LeakCanary﹕ * leaks io.syng.fragment.WebViewFragment instance
08-10 19:01:13.937 1586-4885/io.syng D/LeakCanary﹕ [ 08-10 19:01:13.937 1586: 4885 D/LeakCanary ]
* Reference Key: 23b62bb8-15b9-4593-871a-03ee3d6a2c11

**Comment by dmytyar** [comment]
Have no idea what it related to, Removed anonymous class that extend CordovaInterfaceImpl.
I not see LeakCanary on my device, so can't check if issue gone. If it left - it's inside Cordova sources.

**Comment by jarradh** [comment]
wontfix, cordova issue
